language: node_js
sudo: required
node_js: stable
branches:
  only:
  - hexo
cache:
  apt: true
  yarn: true
  directories:
  - node_modules
install:
- bash deps.sh
- curl -L https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb > /tmp/pandoc.deb
- sudo dpkg -i /tmp/pandoc.deb
- pandoc --version
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- yarn --version
- npm install -g hexo hexo-cli
- yarn install
script:
- git config --global user.name "Haowen Xu"
- git config --global user.email "haowen.xu@outlook.com"
- sed -i "s/__GH_TOKEN__/${GH_TOKEN}/g" ./_config.yml
- hexo generate --deploy
