language: node_js
sudo: required
node_js: stable
branches:
  only:
  - hexo
cache:
  apt: true
  yarn: true
  directories:
  - node_modules
install:
- bash deps.sh
- curl -L https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb
  > /tmp/pandoc.deb
- sudo dpkg -i /tmp/pandoc.deb
- pandoc --version
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- yarn --version
- npm install -g hexo hexo-cli
- yarn install
script:
- git config --global user.name "Haowen Xu"
- git config --global user.email "haowen.xu@outlook.com"
- sed -i "s/__GH_TOKEN__/${GH_TOKEN}/g" ./_config.yml
- hexo generate --deploy
env:
  global:
    secure: RrpdKpVr7rgbu5X6yBX713obFF53HIQl23vXdpz7SoaMysTzipICH+J775Ji6idBo3rAv/JhIWtgqEUsljw+jtSVAuqhpTtwXfjSTJhMLE9pbSdnU9Av1F+gqr9Ddty9ZtusXyZX17snaXCBgTol1CMHoy9KQQAH0qAYIgCO8u/Qo7tBSwy/1rDaeL25VAsj33sd7ymn0tnv3uaV0p6UjV0mYza/vqGWuJGqUpGj3z4zmEjGwBts9/Ojqm3TKxQjfg69srITBTfclQSl3+IrChsXt4el/PjHp9zL6/RDe32v5Zq879A8DV6HHTl5yqaCH6IEvtwBNrjlaQZP6hhd2EnDx4IcQHUJRK8xvKb6kYWrY1lQ7TZ7ov2vpX9PghAdcbCCeBBMRwK8rEuHRDXDFLrCy5Og3r885JP06iWlGNJBlK3P+ZbhDAXGWov0SAjiqXEBsFg6lg2IkMLN0KTf/dtizsqbdZfeltI9Vux6VCYN+T3YKOiL+SZAEsZIjxaysqxOpLIFOo4T1VCQ0+0+6R51oddnqfxq5tDulNZRwzq/FJZgVMsUfmQMWfw/Gly9cmgzxozn8txWWIEZaujAHgphmDBA/KeBwWk18yNZimSn6BgF4NT8kcdIeXZ7LvjFkBqiLSq9B//FnNTUwfSi+8emmrRPI9qERO50cCXUsZ0=
